# Generated by Django 3.1.1 on 2020-09-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
